### ISSUE TITLE
[Question] Add band around points 

### ISSUE THREAD

**Issue by LiorBanai** [benoit-dumas/SplineMesh#39]
Hi,
Great project.
I was wondering if there is  a way to mark the points on the spline curve (maybe with width).
some thing like:
![image](https://user-images.githubusercontent.com/36262995/102871416-13c55b80-4447-11eb-9f2f-86d22563ceb7.png)

I try to create something like tihs:
![image](https://user-images.githubusercontent.com/36262995/102871547-3bb4bf00-4447-11eb-896b-34243b234921.png)

**Comment by benoit-dumas** [comment]
Hi,

You can do a mesh that contains hals the metal part like this :
[image: image.png]

but in this case, the metal part will be bent in the same way than the
tube, which may not be what you need.

You can also have one big mesh with all the metal parts in it, and bend it
in the spline space instead of the curve space.

You an also have a different mesh for the pipe and the metal connexion. You
will have to write a script to apply different meshes on different nodes
(the ExampleTrack file does just that). This way you can add straight nodes
toi avoid the metal part being bent.

Finally, you can also bend only a mesh that represents the pipe, and add
metal parts as static, non-bent meshes at the position you need, using the
ExampleSower or your own script derived from this one. The metal parts will
not be bent but the way the pipe will go through it may not be perfect as
the pipe won't be exactly centered in the metal ring, depending on the
curve.

Hope one of these solutions helps. Have fun bending things!

Ben

Le mar. 22 déc. 2020 à 10:17, Lior Banai <notifications@github.com> a
écrit :

**Comment by LiorBanai** [comment]
Thanks! I'll check those options.

One more question I have, I try to modify the points location in game mode and unable (for example in the example scene the basic pipe). Only in editor mode it is possible. 

What I'm doing wrong?  basically I  have 10 points that are changing over time and I want to model the pipe around them  when they change ( I don't think ropes connection is real close representation).

**Comment by benoit-dumas** [comment]
Do you mean the generated bent content is not updated when you move the
spline nodes at run time? this can be caused by two things
 - check that UpdateInPlayMode is true in SplineMeshTiling component
 - try and uncheck static batching in player settings -> others

Le mar. 22 déc. 2020 à 12:21, Lior Banai <notifications@github.com> a
écrit :

**Comment by LiorBanai** [comment]
now it working (disabling Static batching).
Thanks again!
