### ISSUE TITLE
What is the exact purpose of SplineNode.direction?

### ISSUE THREAD

**Issue by padmalcom** [benoit-dumas/SplineMesh#4]
Hi Benoit, thank you for your great library. I'm wondering if you can explain the purpose of SplineNode.direction in detail. What I'd like to achieve is to avoid "sharp" edges as you can see from the image attached and have the curves point from one SplineNode to the next.

![image](https://user-images.githubusercontent.com/3961950/38676887-c06f2314-3e5c-11e8-97e6-2c65dcd3ffd8.png)

**Comment by benoit-dumas** [comment]
i think wikipedia will be more efficient than me to explain : 

https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Quadratic_curves

In SplineMesh : 

- p0 of the cubic bezier curve is node's position ,
- p1 is node's direction,
- p2 is the opposite of next node's direction in regard of next node's position,
- p3 is next node's position.
Hope it helps !

**Comment by benoit-dumas** [comment]
to avoid the sharp curves, you have to decrease the distance between positions and directions of each node

**Comment by padmalcom** [comment]
Thanks that helped a bit. Trying to figure out how to achive a smooth spline now.

**Comment by benoit-dumas** [comment]
Are you using the spline editor, in editor view? you can drag the positions and directions using handles. I helps a lot to design splines and understand the influence of these points on the final result.

Please take a look at [that video](https://www.youtube.com/watch?v=-iQj0lYbqLE) if you haven't already.

**Comment by padmalcom** [comment]
No I use the spline component for procedural mesh generation where
everything happens in code so far.

__________________________________________________________________________________
*Jonas Freiknecht*
*j.freiknecht@googlemail.com <j.freiknecht@googlemail.com>*
www.jofre.de

2018-04-12 15:57 GMT+02:00 Benoît <notifications@github.com>:

**Comment by benoit-dumas** [comment]
Ok that's what I thought, considering your issue and the screen shot.

So you have to shorten the distance between direction vector and position vector to achieve more smooth curves.

**Comment by nrewkowski** [comment]
In this case, if you're making nodes programmatically like me, "direction" specifically refers to the position of the tangent going OUT of the node (other engines like Unreal might call it exit tangent)

**Comment by benoit-dumas** [comment]
I admit "direction" is a bad choice for that. But now I can't change it for obvious backward compatibility reasons, sorry.

@padmalcom , coming back to that discussion, please note that since we talked, I've added a component named SplineSmoother, which choose direction procedurally. You only have to set a general curvature strength.

This is usefull in most situations, but it can also be a good source of inspiration for your own system.

**Comment by nrewkowski** [comment]
Sure, just wanted others to know that the relative leave tangent to a node
would be (direction-position) if you're calculating it mathematically (from
online numerical analysis resources) or the way that other engines do it
(e.g. I normally use UE4 which already has splines built-in). Thanks for
adding this feature to Unity.

**Comment by Dranak** [comment]
Hi,
Sorry to reborn a closed topic but I don't understand how I can get the "direction" value of a spline node.
With this topic, I now know that it's a "tangent position" but how I can get it for sure.
From context, I'm trying to do a Spline from a AnimationCurve.

![image](https://user-images.githubusercontent.com/8990000/101648995-b094fb80-3a3a-11eb-8230-8ca0092da32d.png)

Best Regards

**Comment by benoit-dumas** [comment]
A SplineNode is:
- a position where the curve pass,
- a control point that control both the tangent of the curve and the curvature (the speed at which the tangent will bend).

In SplineMesh the control point is unintuitively named Direction. This vector is NOT a directionnal one. Instead, the actual direction is the vector between node.Position and node.Direction. It should be called controlPoint but I've never renamed it for backward compatibility purpose.

The vector (node.Direction - node.Position) give two information. Its direction is the tangent of the curve at the node position, and its length is the persistance of this tangent, that defines the curvature of the curve.

If you want to place a node using a direction, you will typically do new Node(Position: nodePosition, Direction: nodePosition + direction * curvature).

Also, note that a curve is define by two nodes n1 and n2. n1.Direction is used to define the tangent at the curve start, and the tangent for the end is the mirror of n2.Direction. SplineMesh only support mirrored tangents between curves, this is a limitation.

Does it help?

**Comment by Dranak** [comment]
Thanks for your fast reply.
It helps a little bit, but I think I need to go deeper to explain my issues. (Sorry to take your time)

So I have try a lot of things but after discover this topic I think I need to absolutely use the keys frame of the AnimationCurve and not just random point of the curve.

In attachment it's my code ATM which manage the Spline.(Sorry for not commented code, it's WIP but normally the code speaks for itself)
I use some of the code of this project. [https://github.com/ken48/BezierToUnityAnimationCurve/blob/master/Curves/Assets/Test.cs](url)
because you said that "Direction" arg is P1 in Bézier Curve theory, so normally my code is mathematically good? Maybe I missed something.

Or maybe I got good data but my spline configuration isn't?
![image](https://user-images.githubusercontent.com/8990000/101662883-51d77e00-3a4a-11eb-83a3-632fb4f54bc8.png)


Thank you again for your help

**Comment by benoit-dumas** [comment]
Let's clarify some things here. Animation curve is a quadratic bezier curve driven by keys, which are the equivalent of SplineNodes.

What I beleive you are doing here is build a AnimationCurve, discretize it in many position samples, then building a spline with these positions, trying to find decent curvature by guessing a direction. This approach is a bit odd but it can work correctly and be usefull.

Indeed, animation curve are able to define nodes with sharp angle because the in and out tangent of a node are not necessarily mirrored. SplineMesh, on the other hand, does not support non-mirrored in/out tangents and won't be able to create a sharp turning. Discretize the curve should then lead to a "more sharp turning". But I doubt that you really need that feature, since you haven't talked about it so far.

As you mentionned, a better solution would be to create one SplineNode for each AnimationCurve key. You have both direction and tangents, so it's trivial.

but the best solution would be to use SplineMesh edition tools and not mess with Animation curve at all. What is your intent and interest in using AnimationCurve? they are hard to edit, heavy to store and limited to two dimensions. Workin with the Spline editor seems way better. You just have to move objects by hand or via code, you can work in three dimensions, you can tweak the up vector...

Can you tell me more about your usecase?

**Comment by Dranak** [comment]
Thanks for you explanation I think I see it more clearly.

So what I want to do, it's to use animation curve to create some variety in my level. The spaceship fly in the pipe created by the spline. I though that will be more efficiency to procedurally create the pipe with Animation Curve because it's easy so modify and configurable but maybe it's overpowered for just that. 
I also think that the transitions between two curves will be smoother and directly at the best position compared to spawn prefab after prefabs.
Maybe, it's again too much overkill for what I want to do

In first place, yes I though that more the spline had points more the mesh created from it will be more defined. Maybe I mixed points and vertex. That is why I get some point of the curve. 

After reading this topic I understand that I only need keyframe data to create the spline and mesh. 
You say it's trivial, maybe I'm stupid, but exactly it's not trivial for me to get that tangent direction to create SplineNode even after so research:/

Thanks again for your time.

**Comment by benoit-dumas** [comment]
The difficulty here is that you try to create a 3D spline en world space, out of a 2D curve in [0;1] space (you can use any interval in AnimationCurves but usually you keep it [0;1]). So you need some 2D/3D conversion.

In AnimationCurves keys, given that the spline goes forward and the splineSize express the extent of the spline in world space:
 - time is the z coordinate in [0;1] space,
 - value is the y coordinate in [0;1] space,
 - tangent is an angle in the 2D space of the curve,
 - weight is the length between Position and Direction, representing the curvature, in [0;1] space.

To get a spline node from such a key, you would do something like that:
spline.Nodes[i].Position = new Vector3(curve.Keys[i].time * splineSize, curve.Keys[i].value * splineSize);
var worldTangent = Quaternion.Euler(curve.Keys[i].outTangent, 0, 0) * Vector3.forward;
var worldWeight = curve.Keys[i].outWeight * splineSize;
spline.Nodes[i].Direction = spline.Nodes[i].Position +  worldTangent * worldWeight

But I still don't understand why you prefer to use AnimationCurves instead of just created splines. Designing your spline is as easy as designing Animation curve, and it is already in the correct space and in 3D.

Also, there is also a autom smoothing component that may help you here. With this component, the direction is automatic and you only have to decide a position for your spline nodes. This is commonly used for procedurally generated spline like I beleive you are trying to do.

Finaly, in SplineMesh, the mathematical definition of the spline is separated from the content generation. You can bend your mesh on any interval of the spline without relying at all on the nodes. The SplineMeshTiling offers a first approach for that, giving the possibility to generate one mesh for each curve, one for the whole spline, or many along the spline using a certain scale. This component is intended to cover 90% of the use cases, and you can esily create your own tiler to tweak the intervals to your specific needs.

**Comment by Dranak** [comment]
Atm I don't want to create my level part(Spline + mesh + obstacles) in the editor because for me it's too strict and we will need creating many prefabs to be efficient.

Once more if I go deeper, I have just one prefab with two triggers BorderStart & BorderEnd that defined a level part.
In level script who mange all this magic I can tweak so value to generate this level at runtime.
For example I can set a range of number of obstacles and a spacing between them.
With that I get the length (Z axis) of this level part and set the border at the good position.
With this length I can define the MaxSizeY, it's arbitrary but I define it like length/2;

Finally with this data I can generate all level I desire and tweak them, for example the difficulty curve by reducing the spacing value between obstacles.

I don't know if it's understandable, hope so '.

I will keep you posted if it's works and how I utilize your beautiful tool;)

Thank for you, help and time.
