### ISSUE TITLE
[Question] Extend spline past the end points

### ISSUE THREAD

**Issue by LiorBanai** [benoit-dumas/SplineMesh#41]
Hi,
I managed to create catheter like spline.
Is there a way to extend the curve/spline past the endppoints by a distance (say 1 millimeter) without artificially adding 2 points and hide them?
 
![image](https://user-images.githubusercontent.com/36262995/103197514-d0f3ff80-48ee-11eb-8471-35cf1b81d2cc.png)

**Comment by LiorBanai** [comment]
Do you have any idea how to implement this? ideally the extra spline will have different colors..

**Comment by benoit-dumas** [comment]
I don't understand exactly what you are trying to acheive. You cannot bend anything past the spline first and last nodes because the direction alone is not sufficient to do the Bezier math. But it is totally possible to have different content bent on the different curves of the spline, by using a custom script like the ExampleTrack (that is not showcased in the shocase scene but present in the code).

Also, depending on what you need, you can place a mesh on a node like in the ExampleSower, for example to create a non-deformed head at the tip of a deformed snake body. This head can go beyond the end of the spline but no deformation occur on it.

Sorry I didn't found your message earlier. please provide more details if these suggestions don't fit your need, and ring me again if I'm not answering fast enough

**Comment by LiorBanai** [comment]
I wasn't clear in my question. basically I would like the spline to "blend over/continue" in same direction of the end/start spline by some value. in the above image I would like extension in this way (no bending just continuation of the spline in straight line):
![image](https://user-images.githubusercontent.com/36262995/107888488-29ba3e80-6f15-11eb-8cb9-d06e08586f87.png)
